var N = null;var sourcesIndex = {};
sourcesIndex["bitflags"] = {"name":"","files":["lib.rs"]};
sourcesIndex["block"] = {"name":"","files":["lib.rs"]};
sourcesIndex["cocoa"] = {"name":"","files":["appkit.rs","base.rs","foundation.rs","lib.rs","quartzcore.rs"]};
sourcesIndex["core_foundation"] = {"name":"","files":["array.rs","attributed_string.rs","base.rs","boolean.rs","bundle.rs","data.rs","date.rs","dictionary.rs","error.rs","filedescriptor.rs","lib.rs","number.rs","propertylist.rs","runloop.rs","set.rs","string.rs","timezone.rs","url.rs","uuid.rs"]};
sourcesIndex["core_foundation_sys"] = {"name":"","files":["array.rs","attributed_string.rs","base.rs","bundle.rs","data.rs","date.rs","dictionary.rs","error.rs","filedescriptor.rs","lib.rs","messageport.rs","number.rs","propertylist.rs","runloop.rs","set.rs","string.rs","timezone.rs","url.rs","uuid.rs"]};
sourcesIndex["core_graphics"] = {"name":"","files":["base.rs","color.rs","color_space.rs","context.rs","data_provider.rs","display.rs","event.rs","event_source.rs","font.rs","geometry.rs","image.rs","lib.rs","path.rs","private.rs","sys.rs","window.rs"]};
sourcesIndex["darwin_webkit"] = {"name":"","dirs":[{"name":"foundation","files":["mod.rs","ns_url.rs","ns_url_bookmark_creation_options.rs","ns_url_bookmark_resolution_options.rs","ns_url_request.rs"]},{"name":"helpers","files":["dwk_app.rs","dwk_webview.rs","mod.rs"]},{"name":"webkit","files":["mod.rs","wk_navigation.rs","wk_script_message_handler.rs","wk_web_view.rs","wk_web_view_configuration.rs"]}],"files":["lib.rs"]};
sourcesIndex["dispatch"] = {"name":"","files":["ffi.rs","group.rs","lib.rs","once.rs","queue.rs","sem.rs"]};
sourcesIndex["foreign_types"] = {"name":"","files":["lib.rs"]};
sourcesIndex["foreign_types_shared"] = {"name":"","files":["lib.rs"]};
sourcesIndex["libc"] = {"name":"","dirs":[{"name":"unix","dirs":[{"name":"bsd","dirs":[{"name":"apple","dirs":[{"name":"b64","dirs":[{"name":"x86_64","files":["align.rs","mod.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["fixed_width_ints.rs","lib.rs","macros.rs"]};
sourcesIndex["malloc_buf"] = {"name":"","files":["lib.rs"]};
sourcesIndex["objc"] = {"name":"","dirs":[{"name":"message","dirs":[{"name":"apple","files":["mod.rs","x86_64.rs"]}],"files":["mod.rs","verify.rs"]},{"name":"rc","files":["autorelease.rs","mod.rs","strong.rs","weak.rs"]}],"files":["declare.rs","encode.rs","lib.rs","macros.rs","runtime.rs"]};
createSourceSidebar();
